import type { AnnouncementAudience, NotificationSeverity, Prisma } from '@prisma/client';
import type { Request } from 'express';
import { prisma } from '../../core/db.js';
import { badRequest, notFound } from '../../core/errors.js';
import { logger } from '../../core/logger.js';
import * as audit from '../admin/audit/audit.service.js';

/**
 * Announcements.
 *
 * A notification is generated by something that happened to one person. An
 * announcement is written by a human for an audience — so it gets a draft
 * state, a review, and a publish step, because the cost of a typo is different
 * when it reaches everybody at once.
 *
 * Publishing fans out to a notification per member. That is deliberate: it
 * means an announcement lands in the same bell as everything else, gets the
 * same read state, and cannot be missed by someone who never visits a separate
 * "announcements" page.
 */

export interface UpsertInput {
  id?: string;
  title: string;
  body: string;
  severity?: NotificationSeverity;
  audience?: AnnouncementAudience;
  link?: string;
  pinned?: boolean;
  expiresAt?: string | null;
}

export async function list(opts: { take?: number; skip?: number } = {}) {
  const [rows, total] = await Promise.all([
    prisma.announcement.findMany({
      orderBy: { createdAt: 'desc' },
      take: Math.min(opts.take ?? 25, 100),
      skip: opts.skip ?? 0,
    }),
    prisma.announcement.count(),
  ]);
  return { total, rows };
}

export async function upsert(adminId: string, input: UpsertInput, req?: Request) {
  const title = input.title.trim();
  const body = input.body.trim();
  if (title.length < 3) throw badRequest('Give it a title members will understand');
  if (body.length < 10) throw badRequest('The message is too short to be useful');

  const data = {
    title,
    body,
    severity: input.severity ?? 'INFO',
    audience: input.audience ?? 'ALL',
    link: input.link?.trim() || null,
    pinned: input.pinned ?? false,
    expiresAt: input.expiresAt ? new Date(input.expiresAt) : null,
  };

  if (input.id) {
    const existing = await prisma.announcement.findUnique({ where: { id: input.id } });
    if (!existing) throw notFound('Announcement not found');
    // Editing what has already been sent would rewrite what members were told.
    if (existing.status === 'PUBLISHED') {
      throw badRequest('This has already been sent. Withdraw it first, or write a new one.');
    }
    const row = await prisma.announcement.update({ where: { id: input.id }, data });
    await audit.record({
      adminId, action: 'UPDATE', entityType: 'announcement', entityId: row.id,
      summary: `Edited draft announcement “${row.title}”`, req,
    });
    return row;
  }

  const row = await prisma.announcement.create({ data: { ...data, createdBy: adminId } });
  await audit.record({
    adminId, action: 'CREATE', entityType: 'announcement', entityId: row.id,
    summary: `Drafted announcement “${row.title}”`, req,
  });
  return row;
}

/**
 * Sends it.
 *
 * The fan-out is one notification row plus one recipient row per member, in a
 * single insert each, rather than a loop of individual notifications — on a
 * large member base the difference is a query and a minute.
 */
export async function publish(adminId: string, id: string, req?: Request) {
  const row = await prisma.announcement.findUnique({ where: { id } });
  if (!row) throw notFound('Announcement not found');
  if (row.status === 'PUBLISHED') throw badRequest('This has already been sent');

  const where = audienceFilter(row.audience);
  const members = await prisma.user.findMany({ where, select: { id: true } });

  if (!members.length) {
    throw badRequest('No members match that audience, so this would reach nobody');
  }

  const published = await prisma.$transaction(async (tx) => {
    const notification = await tx.notification.create({
      data: {
        type: 'announcement',
        category: 'SYSTEM',
        severity: row.severity,
        title: row.title,
        body: row.body,
        link: row.link,
        // One announcement can only ever be sent once, however many times the
        // button is pressed.
        dedupeKey: `announcement:${row.id}`,
        expiresAt: row.expiresAt,
        meta: { announcementId: row.id },
      },
    });

    await tx.notificationRecipient.createMany({
      data: members.map((m) => ({
        notificationId: notification.id,
        actorType: 'USER' as const,
        actorId: m.id,
      })),
      skipDuplicates: true,
    });

    return tx.announcement.update({
      where: { id },
      data: { status: 'PUBLISHED', publishedAt: new Date(), deliveredTo: members.length },
    });
  }, { timeout: 60_000 });

  logger.info({ id, members: members.length }, 'announcement published');
  await audit.record({
    adminId, action: 'UPDATE', entityType: 'announcement', entityId: id,
    summary: `Published “${row.title}” to ${members.length} member${members.length === 1 ? '' : 's'}`,
    after: { audience: row.audience, deliveredTo: members.length }, req,
  });
  return published;
}

/** Takes it down. Notifications already delivered are left alone — they were read. */
export async function withdraw(adminId: string, id: string, req?: Request) {
  const row = await prisma.announcement.update({
    where: { id },
    data: { status: 'WITHDRAWN' },
  });
  await audit.record({
    adminId, action: 'UPDATE', entityType: 'announcement', entityId: id,
    summary: `Withdrew “${row.title}” — the banner is gone, notifications already sent remain`, req,
  });
  return row;
}

export async function remove(adminId: string, id: string, req?: Request) {
  const row = await prisma.announcement.findUnique({ where: { id } });
  if (!row) throw notFound('Announcement not found');
  if (row.status === 'PUBLISHED') throw badRequest('Withdraw it before deleting');

  await prisma.announcement.delete({ where: { id } });
  await audit.record({
    adminId, action: 'DELETE', entityType: 'announcement', entityId: id,
    summary: `Deleted draft “${row.title}”`, req,
  });
}

const audienceFilter = (audience: AnnouncementAudience): Prisma.UserWhereInput => {
  const base: Prisma.UserWhereInput = { status: 'ACTIVE' };
  if (audience === 'INVESTED') return { ...base, investments: { some: {} } };
  if (audience === 'NOT_INVESTED') return { ...base, investments: { none: {} } };
  return base;
};

// ── member side ───────────────────────────────────────────────────────────

/** Pinned banners this member has not dismissed and that have not expired. */
export async function bannersFor(userId: string) {
  const now = new Date();
  const rows = await prisma.announcement.findMany({
    where: {
      status: 'PUBLISHED',
      pinned: true,
      OR: [{ expiresAt: null }, { expiresAt: { gt: now } }],
      dismissals: { none: { userId } },
    },
    orderBy: { publishedAt: 'desc' },
    take: 3,
    select: { id: true, title: true, body: true, severity: true, link: true, publishedAt: true },
  });
  return rows;
}

export async function dismiss(userId: string, announcementId: string) {
  await prisma.announcementDismissal.upsert({
    where: { announcementId_userId: { announcementId, userId } },
    create: { announcementId, userId },
    update: {},
  });
  return { ok: true };
}
